name: scphere_test
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib==3.5.3
  - pandas==1.3.5
  - pytorch==1.12.1
  - seaborn==0.12.2
  - colorcet==3.0.1
  - pyshp==2.1.3
  - scipy==1.7.3
  - python==3.7.16
  - numpy==1.21.5
  - jupyter==1.0.0